### PR TITLE
Douglas Allen's Completed Assignment Now Ready For Review.  Upwork Profile Link: https://www.upwork.com/freelancers/~01bbd1b7406c480bbe

### PR DESCRIPTION
**Pull request by cartel1**
1) This is now a Java 8 eclipse project.
2) The original parser-exercise folder has been overwritten after exporting the new Eclipse project.
3) You can go straight to the GrouponPurchaseParserV2.java file for a review.
4) All tests have passed successfully.
5) I had problems getting the getShipping() method of the EcommerceReceipt class to work as documented.  It wasn't working so I had to do an override on the getShipping() method to be able to get the populated shipping address object.
6) A nice project overall.  It was properly documented and the edataSource helper APIs did come in handy.  I hope the solution is to your liking.

### CODE REVIEW

**Comment by cadams500** [comment]
Thanks, Douglas.  
I will also have our internal team look at the shipping issue you ran into. It's quite confusing right now, because of some of the backward compatibility required for the UI; it does work, but it clearly was confusing enough that you came up with a nice workaround :)

We'll be making final determinations early next week. Hope you have a great weekend.

**Comment by cartel1** [comment]
Thanks for the positive review and confirmation Mr. Adams.

I hope you have a great weekend as well.

Kind Regards,
DA.

**Comment by cartel1** [comment]
Hi Mr. Adams,

I apologize for having to use multiple channels to contact you, but I feel this is necessary as Upwork was down for a significant number of hours yesterday and so I am not sure if you would have been receiving my messages.

I just wanted to follow up on this job post.

Is this project still active?

Will eDatasource be making a decision this week on the status of this project?

Thank you.

Kind Regards,
DA.

**Comment by brandonglesmann** [comment]
Douglas,

We have been going through the code samples submitted, and currently your code sample is one of the samples that is in our top group. We will be sending more details to all of the applicants later today.

We are currently waiting on an internal contract finalization prior to moving forward with this work. We expect to be moving forward in the next week or two. Though, this project will not happen with out that internal contract. Currently, all indications are that the contract will go through. Unfortunately there are no guarantees, so we understand that you may have other opportunities that come up in the mean time. 

We hope that our project will get green lit, and if it does we hope you will be able to join our team.

Regards,
Brandon Glesmann

**Comment by cartel1** [comment]
Thanks for this prompt feedback Mr. Glesmann including the positive review of my sample code.

I really enjoyed working on the assignment and I was very impressed with the clarity of instruction given and the quality documentation and API tools that were made available to me. 

I hope your project gets green lit soon, and would be happy to join the eDatasource team.

Thank you.

Kind Regards,
DA.

**Comment by cartel1** [comment]
Hello Mr. Glesmann,

Today Mr. Adams informed me that that Edatasource was able to obtain the contract for the project that you would like me to work on.

I had replied to Mr. Adams via Upwork earlier confirming that I would be available to start working this week, but I am not sure if he had received the message since Upwork has been having major technical issues lately.

Please convey my confirmation to Mr. Adams so that he can provide me with the relevant project details this week for my initial review.

Thank you, and congratulations on closing the deal.

Kind Regards,
DA.

**Pull request closed without merging**
